package handler

import (
	"log/slog"
	"net/http"
	"time"

	"github.com/xuzhiping7/ai-kanban/internal/domain"
	"github.com/xuzhiping7/ai-kanban/internal/githost"
	"github.com/xuzhiping7/ai-kanban/internal/service"
)

// --- Git conflict resolution handlers ---

// gitConflictsAbort handles POST /api/workspaces/{id}/git/conflicts/abort.
func (h *Handler) gitConflictsAbort(w http.ResponseWriter, r *http.Request) {
	id, ok := parseUUID(w, r, "id")
	if !ok {
		return
	}

	var req struct {
		RepoID string `json:"repo_id"`
	}
	if !decodeJSON(w, r, &req) {
		return
	}

	repos, _ := h.wsRepoRepo.FindByWorkspaceIDWithRepos(id)
	target := findRepoByID(repos, req.RepoID)
	if target == nil {
		badRequest(w, "repo not found in workspace")
		return
	}

	if err := h.gitSvc.AbortConflicts(target.Path); err != nil {
		internalError(w, "failed to abort conflicts: "+err.Error())
		return
	}
	success(w, map[string]string{"status": "aborted"})
}

// gitRebaseContinue handles POST /api/workspaces/{id}/git/rebase/continue.
func (h *Handler) gitRebaseContinue(w http.ResponseWriter, r *http.Request) {
	id, ok := parseUUID(w, r, "id")
	if !ok {
		return
	}

	var req struct {
		RepoID string `json:"repo_id"`
	}
	if !decodeJSON(w, r, &req) {
		return
	}

	repos, _ := h.wsRepoRepo.FindByWorkspaceIDWithRepos(id)
	target := findRepoByID(repos, req.RepoID)
	if target == nil {
		badRequest(w, "repo not found in workspace")
		return
	}

	if err := h.gitSvc.ContinueRebase(target.Path); err != nil {
		internalError(w, "failed to continue rebase: "+err.Error())
		return
	}
	success(w, map[string]string{"status": "continued"})
}

// gitForcePush handles POST /api/workspaces/{id}/git/push/force.
func (h *Handler) gitForcePush(w http.ResponseWriter, r *http.Request) {
	id, ok := parseUUID(w, r, "id")
	if !ok {
		return
	}

	ws, err := h.wsRepo.FindByID(id)
	if err != nil || ws == nil {
		notFound(w, "workspace not found")
		return
	}

	var req struct {
		RepoID string `json:"repo_id"`
	}
	if !decodeJSON(w, r, &req) {
		return
	}

	repos, _ := h.wsRepoRepo.FindByWorkspaceIDWithRepos(id)
	var results []map[string]string
	for _, rwt := range repos {
		if req.RepoID != "" && rwt.ID.String() != req.RepoID {
			continue
		}
		err := h.gitSvc.PushToRemote(rwt.Path, ws.Branch, true)
		status := "pushed"
		errMsg := ""
		if err != nil {
			status = "error"
			errMsg = err.Error()
		}
		results = append(results, map[string]string{
			"repo_id": rwt.ID.String(),
			"status":  status,
			"error":   errMsg,
		})
	}
	success(w, results)
}

// --- PR workflow handlers ---

// createPR handles POST /api/workspaces/{id}/pull-requests.
func (h *Handler) createPR(w http.ResponseWriter, r *http.Request) {
	id, ok := parseUUID(w, r, "id")
	if !ok {
		return
	}

	if !h.ghCLI.IsInstalled() {
		errorWithData(w, http.StatusBadRequest, "GitHub CLI not installed", map[string]string{
			"type":     "cli_not_installed",
			"provider": "GitHub",
		})
		return
	}

	ws, err := h.wsRepo.FindByID(id)
	if err != nil || ws == nil {
		notFound(w, "workspace not found")
		return
	}

	var req struct {
		Title                   string  `json:"title"`
		Body                    *string `json:"body"`
		TargetBranch            *string `json:"target_branch"`
		Draft                   *bool   `json:"draft"`
		RepoID                  string  `json:"repo_id"`
		AutoGenerateDescription bool    `json:"auto_generate_description"`
	}
	if !decodeJSON(w, r, &req) {
		return
	}
	if req.Title == "" {
		badRequest(w, "title is required")
		return
	}

	repos, _ := h.wsRepoRepo.FindByWorkspaceIDWithRepos(id)
	target := findRepoByID(repos, req.RepoID)
	if target == nil {
		badRequest(w, "repo not found in workspace")
		return
	}

	baseBranch := target.TargetBranch
	if req.TargetBranch != nil && *req.TargetBranch != "" {
		baseBranch = *req.TargetBranch
	}

	// Push current branch first.
	if err := h.gitSvc.PushToRemote(target.Path, ws.Branch, false); err != nil {
		slog.Warn("创建 PR 前推送失败", "error", err)
	}

	// Determine repo owner/name from remote URL.
	remote, err := h.gitSvc.GetDefaultRemote(target.Path)
	if err != nil {
		internalError(w, "failed to get remote: "+err.Error())
		return
	}
	repoName, err := githost.ParseRepoFromURL(remote.URL)
	if err != nil {
		internalError(w, "failed to parse repo URL: "+err.Error())
		return
	}

	body := ""
	if req.Body != nil {
		body = *req.Body
	}
	draft := false
	if req.Draft != nil {
		draft = *req.Draft
	}

	prURL, err := h.ghCLI.CreatePR(githost.CreatePROptions{
		Repo:  repoName,
		Head:  ws.Branch,
		Base:  baseBranch,
		Title: req.Title,
		Body:  body,
		Draft: draft,
	})
	if err != nil {
		errorWithData(w, http.StatusInternalServerError, "failed to create PR: "+err.Error(), map[string]string{
			"type": "cli_error",
		})
		return
	}

	created(w, map[string]string{"url": prURL})
}

// attachPR handles POST /api/workspaces/{id}/pull-requests/attach.
func (h *Handler) attachPR(w http.ResponseWriter, r *http.Request) {
	id, ok := parseUUID(w, r, "id")
	if !ok {
		return
	}

	if !h.ghCLI.IsInstalled() {
		errorWithData(w, http.StatusBadRequest, "GitHub CLI not installed", map[string]string{
			"type":     "cli_not_installed",
			"provider": "GitHub",
		})
		return
	}

	ws, err := h.wsRepo.FindByID(id)
	if err != nil || ws == nil {
		notFound(w, "workspace not found")
		return
	}

	var req struct {
		RepoID string `json:"repo_id"`
	}
	if !decodeJSON(w, r, &req) {
		return
	}

	repos, _ := h.wsRepoRepo.FindByWorkspaceIDWithRepos(id)
	target := findRepoByID(repos, req.RepoID)
	if target == nil {
		badRequest(w, "repo not found in workspace")
		return
	}

	remote, err := h.gitSvc.GetDefaultRemote(target.Path)
	if err != nil {
		internalError(w, "failed to get remote: "+err.Error())
		return
	}
	repoName, err := githost.ParseRepoFromURL(remote.URL)
	if err != nil {
		internalError(w, "failed to parse repo URL: "+err.Error())
		return
	}

	prs, err := h.ghCLI.ListPRsForBranch(repoName, ws.Branch)
	if err != nil {
		internalError(w, "failed to list PRs: "+err.Error())
		return
	}

	if len(prs) == 0 {
		success(w, map[string]any{
			"pr_attached": false,
			"pr_url":      nil,
			"pr_number":   nil,
			"pr_status":   nil,
		})
		return
	}

	pr := prs[0]
	success(w, map[string]any{
		"pr_attached": true,
		"pr_url":      pr.URL,
		"pr_number":   pr.Number,
		"pr_status":   pr.Status,
	})
}

// getPRComments handles GET /api/workspaces/{id}/pull-requests/comments.
func (h *Handler) getPRComments(w http.ResponseWriter, r *http.Request) {
	id, ok := parseUUID(w, r, "id")
	if !ok {
		return
	}

	if !h.ghCLI.IsInstalled() {
		errorWithData(w, http.StatusBadRequest, "GitHub CLI not installed", map[string]string{
			"type":     "cli_not_installed",
			"provider": "GitHub",
		})
		return
	}

	repoID := getQuery(r, "repo_id")
	if repoID == "" {
		badRequest(w, "repo_id query parameter is required")
		return
	}

	repos, _ := h.wsRepoRepo.FindByWorkspaceIDWithRepos(id)
	target := findRepoByID(repos, repoID)
	if target == nil {
		badRequest(w, "repo not found in workspace")
		return
	}

	ws, err := h.wsRepo.FindByID(id)
	if err != nil || ws == nil {
		notFound(w, "workspace not found")
		return
	}

	remote, err := h.gitSvc.GetDefaultRemote(target.Path)
	if err != nil {
		internalError(w, "failed to get remote: "+err.Error())
		return
	}
	repoName, err := githost.ParseRepoFromURL(remote.URL)
	if err != nil {
		internalError(w, "failed to parse repo URL: "+err.Error())
		return
	}

	prs, err := h.ghCLI.ListPRsForBranch(repoName, ws.Branch)
	if err != nil || len(prs) == 0 {
		success(w, map[string]any{"comments": []any{}})
		return
	}

	comments, err := h.ghCLI.GetPRComments(repoName, prs[0].Number)
	if err != nil {
		slog.Warn("获取 PR 评论失败", "error", err)
		success(w, map[string]any{"comments": []any{}})
		return
	}
	success(w, map[string]any{"comments": comments})
}

// createWorkspaceFromPR handles POST /api/workspaces/from-pr.
func (h *Handler) createWorkspaceFromPR(w http.ResponseWriter, r *http.Request) {
	var req struct {
		RepoID     string `json:"repo_id"`
		PRNumber   int    `json:"pr_number"`
		PRTitle    string `json:"pr_title"`
		PRURL      string `json:"pr_url"`
		HeadBranch string `json:"head_branch"`
		BaseBranch string `json:"base_branch"`
	}
	if !decodeJSON(w, r, &req) {
		return
	}
	if req.RepoID == "" || req.PRNumber == 0 {
		badRequest(w, "repo_id and pr_number are required")
		return
	}

	repoID, err := domain.ParseUUID(req.RepoID)
	if err != nil {
		badRequest(w, "invalid repo_id")
		return
	}

	repo, err := h.repoSvc.GetByID(repoID)
	if err != nil || repo == nil {
		notFound(w, "repo not found")
		return
	}

	now := time.Now().UTC().Truncate(time.Microsecond)
	ws := &domain.Workspace{
		ID:        domain.NewUUID(),
		Branch:    req.HeadBranch,
		Name:      &req.PRTitle,
		CreatedAt: now,
		UpdatedAt: now,
	}
	if err := h.wsRepo.Create(ws); err != nil {
		internalError(w, "failed to create workspace: "+err.Error())
		return
	}

	_ = h.wsRepoRepo.CreateMany(ws.ID, []domain.CreateWorkspaceRepo{{
		RepoID:       repoID,
		TargetBranch: req.BaseBranch,
	}})

	h.eventSvc.NotifyChange(service.HookTableWorkspaces, service.HookOpInsert, ws.ID)
	created(w, ws)
}

// --- Helper ---

// findRepoByID finds a repo in the list by its ID string.
func findRepoByID(repos []domain.RepoWithTargetBranch, id string) *domain.RepoWithTargetBranch {
	if id == "" {
		if len(repos) > 0 {
			return &repos[0]
		}
		return nil
	}
	for _, r := range repos {
		if r.ID.String() == id {
			return &r
		}
	}
	return nil
}
