name: 'Go checks common setup'
description: 'Common setup for Go checks in CI'

inputs:
  go-version:
    description: 'Go version'
    required: false
    default: '1.24'
  setup-node:
    description: 'Whether to install Node.js and pnpm'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      if: ${{ inputs.setup-node == 'true' }}
      uses: ./.github/actions/setup-node

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
